import { GoogleGenAI, Type } from "@google/genai";
import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "30mb" }));

// Helper to initialize server-side Gemini client securely
function getAiClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY environment variable is not defined.");
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
}

// Health check endpoint
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

// Test local Ollama / LM Studio endpoint reachability
app.post("/api/test-local-model", async (req, res) => {
  const { ollamaUrl = "http://localhost:11434", ollamaModel = "llama3.2" } = req.body;
  try {
    const cleanUrl = ollamaUrl.replace(/\/+$/, "");
    const testRes = await fetch(`${cleanUrl}/api/tags`, { method: "GET" });
    if (testRes.ok) {
      const data: any = await testRes.json();
      const models = data.models ? data.models.map((m: any) => m.name) : [];
      return res.json({
        status: "ok",
        message: `Kết nối thành công đến Local Ollama tại ${cleanUrl}!`,
        availableModels: models,
      });
    }
    return res.status(400).json({
      error: `Không thể kết nối đến Ollama tại ${cleanUrl}. Vui lòng mở Ollama và chạy: 'ollama run ${ollamaModel}'`,
    });
  } catch (err: any) {
    return res.status(500).json({
      error: `Chưa kết nối được Local LLM (${ollamaUrl}): ${err.message || 'Connection refused'}. Mẹo: Hãy dùng chế độ 'Local Fast (Chạy Offline SIÊU NHANH)' để dùng không cần tải server!`,
    });
  }
});

// Analyze session transcript endpoint with structured meeting intelligence schema
app.post("/api/analyze-session", async (req, res) => {
  try {
    const {
      transcript,
      durationSeconds = 0,
      meetingContext = null,
      topicHint = "",
      engineType = "gemini",
      ollamaUrl = "http://localhost:11434",
      ollamaModel = "llama3.2",
    } = req.body;

    if (!transcript || typeof transcript !== "string" || transcript.trim().length === 0) {
      return res.status(400).json({ error: "Transcript text is required for analysis." });
    }

    const meetingTitle = meetingContext?.title || topicHint || "Meeting Session";
    const meetingObjective = meetingContext?.objective || "Extract structured meeting intelligence and action items.";
    const expectedOutcome = meetingContext?.expectedOutcome || "Clear actionable decisions, next steps, and risks.";
    const watchList = Array.isArray(meetingContext?.watchList) && meetingContext.watchList.length > 0
      ? meetingContext.watchList.join(", ")
      : "unresolved technical issues, owners, deadlines, decisions, risks, data quality problems";

    // Check if user requested Local Ollama server
    if (engineType === "local-ollama") {
      try {
        const cleanUrl = ollamaUrl.replace(/\/+$/, "");
        const ollamaPrompt = `You are a professional meeting intelligence AI assistant (like Notion AI).
Analyze this meeting transcript with objective "${meetingObjective}":
"${transcript}"

Return ONLY a valid JSON object strictly matching this schema:
{
  "title": "${meetingTitle}",
  "objective": "${meetingObjective}",
  "executiveSummary": "2-4 sentence executive summary",
  "decisions": [{"decision": "string", "context": "string", "timestamp": 0}],
  "actionItems": [{"task": "string", "owner": "string or Not specified", "deadline": "string or Not specified", "priority": "high", "timestamp": 0}],
  "importantPoints": [{"topic": "string", "detail": "string", "timestamp": 0}],
  "risks": [{"risk": "string", "impact": "string", "suggestedFollowUp": "string"}],
  "openQuestions": ["string"],
  "followUps": ["string"],
  "sentiment": "string"
}
CRITICAL RULE: Never invent an owner or deadline. Use 'Not specified' if not explicitly stated in transcript.`;

        const ollamaRes = await fetch(`${cleanUrl}/api/generate`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            model: ollamaModel,
            prompt: ollamaPrompt,
            stream: false,
            format: "json",
          }),
        });

        if (ollamaRes.ok) {
          const ollamaData: any = await ollamaRes.json();
          if (ollamaData.response) {
            const parsed = JSON.parse(ollamaData.response);
            return res.json({
              title: parsed.title || meetingTitle,
              objective: parsed.objective || meetingObjective,
              executiveSummary: parsed.executiveSummary || parsed.summary || "Summary generated by local model.",
              summary: parsed.executiveSummary || parsed.summary || "Summary generated by local model.",
              decisions: parsed.decisions || [],
              actionItems: parsed.actionItems || [],
              importantPoints: parsed.importantPoints || [],
              risks: parsed.risks || [],
              openQuestions: parsed.openQuestions || [],
              followUps: parsed.followUps || [],
              keyTopics: parsed.keyTopics || [],
              keyTakeaways: parsed.keyTakeaways || [],
              sentiment: parsed.sentiment || "Local Model Analysis",
              wordCount: transcript.split(/\s+/).length,
            });
          }
        }
      } catch (ollamaErr: any) {
        console.warn("Ollama local connection failed, falling back to Gemini/local fast engine:", ollamaErr);
      }
    }

    const ai = getAiClient();

    const prompt = `You are a world-class Executive Meeting Intelligence AI (similar to a lightweight Notion AI meeting assistant).
Analyze the following meeting transcript and produce comprehensive, actionable meeting intelligence strictly aligned with the defined meeting objective.

=== MEETING CONTEXT ===
- Meeting Title: ${meetingTitle}
- Meeting Objective: ${meetingObjective}
- Expected Outcome: ${expectedOutcome}
- Key Items to Watch For: ${watchList}
- Total Duration: ${Math.round(durationSeconds)} seconds

=== TRANSCRIPT ===
"""
${transcript}
"""

=== CRITICAL INSTRUCTIONS ===
1. Analyze both [Me] (Microphone) and [Meeting] (System/Participants) remarks.
2. Link every decision, action item, and important point to an integer timestamp (in seconds) corresponding to when that discussion occurred in the transcript.
3. NEVER INVENT AN OWNER OR DEADLINE. If the transcript does not explicitly name an owner or deadline, write EXACTLY "Not specified".
4. Identify real operational or technical risks with concrete impacts and suggested follow-ups.
5. Capture open questions that were left unanswered during the meeting.
6. Provide an executive summary of 2-4 dense, high-impact sentences.
`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            title: { type: Type.STRING },
            objective: { type: Type.STRING },
            executiveSummary: { type: Type.STRING },
            decisions: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  decision: { type: Type.STRING },
                  context: { type: Type.STRING },
                  timestamp: { type: Type.INTEGER },
                },
                required: ["decision", "context", "timestamp"],
              },
            },
            actionItems: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  task: { type: Type.STRING },
                  owner: { type: Type.STRING },
                  deadline: { type: Type.STRING },
                  priority: { type: Type.STRING },
                  timestamp: { type: Type.INTEGER },
                },
                required: ["task", "owner", "deadline", "priority", "timestamp"],
              },
            },
            importantPoints: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  topic: { type: Type.STRING },
                  detail: { type: Type.STRING },
                  timestamp: { type: Type.INTEGER },
                },
                required: ["topic", "detail", "timestamp"],
              },
            },
            risks: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  risk: { type: Type.STRING },
                  impact: { type: Type.STRING },
                  suggestedFollowUp: { type: Type.STRING },
                },
                required: ["risk", "impact", "suggestedFollowUp"],
              },
            },
            openQuestions: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
            },
            followUps: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
            },
            sentiment: { type: Type.STRING },
            wordCount: { type: Type.INTEGER },
          },
          required: [
            "title",
            "objective",
            "executiveSummary",
            "decisions",
            "actionItems",
            "importantPoints",
            "risks",
            "openQuestions",
            "followUps",
            "sentiment"
          ],
        },
      },
    });

    const responseText = response.text;
    if (!responseText) {
      throw new Error("Empty response returned from Gemini API.");
    }

    const analysis = JSON.parse(responseText);

    // Populate backward-compatibility fields for legacy views
    analysis.summary = analysis.executiveSummary;
    analysis.keyTopics = analysis.importantPoints.map((p: any) => ({
      topic: p.topic,
      details: [p.detail],
    }));
    analysis.keyTakeaways = analysis.decisions.map((d: any) => d.decision);
    if (!analysis.wordCount) {
      analysis.wordCount = transcript.split(/\s+/).length;
    }

    res.json(analysis);
  } catch (err: any) {
    handleApiError(res, err, "Failed to analyze meeting session");
  }
});

function handleApiError(res: express.Response, err: any, defaultMsg: string) {
  console.error("Gemini API Error:", err);
  const errMsg = err?.message || String(err);
  if (errMsg.includes("429") || errMsg.includes("RESOURCE_EXHAUSTED") || errMsg.includes("Quota exceeded")) {
    return res.status(429).json({
      error: "⚠️ Đã vượt quá hạn ngạch API Gemini miễn phí (20 request/ngày). Hãy chờ vài phút rồi bấm Phân tích AI lại! Lưu ý: Đoạn thu âm Web Speech API của bạn vẫn được lưu 100%."
    });
  }
  return res.status(500).json({ error: errMsg || defaultMsg });
}

// Q&A / Ask questions about session transcript endpoint
app.post("/api/ask-session", async (req, res) => {
  try {
    const {
      transcript,
      question,
      engineType = "gemini",
      ollamaUrl = "http://localhost:11434",
      ollamaModel = "llama3.2",
    } = req.body;

    if (!transcript || !question) {
      return res.status(400).json({ error: "Both transcript and question are required." });
    }

    if (engineType === "local-ollama") {
      try {
        const cleanUrl = ollamaUrl.replace(/\/+$/, "");
        const ollamaRes = await fetch(`${cleanUrl}/api/generate`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            model: ollamaModel,
            prompt: `Transcript context:\n"""\n${transcript}\n"""\n\nQuestion: "${question}"\n\nAnswer concisely based on the transcript context above:`,
            stream: false,
          }),
        });

        if (ollamaRes.ok) {
          const ollamaData: any = await ollamaRes.json();
          if (ollamaData.response) {
            return res.json({ answer: `💻 [Local Model (${ollamaModel})]: ${ollamaData.response}` });
          }
        }
      } catch (ollamaErr: any) {
        console.warn("Ollama ask-session failed, falling back to Gemini/Local Fast:", ollamaErr);
      }
    }

    const ai = getAiClient();

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: `You are an intelligent AI note assistant answering questions based strictly on a recorded English audio transcript.

Transcript context:
"""
${transcript}
"""

User Question: "${question}"

Provide a direct, helpful, and concise answer based on the transcript above. If the information isn't mentioned in the transcript, state so politely and provide your best relevant knowledge while clarifying it wasn't explicitly discussed in the recording. You may answer in English or Vietnamese if the question is in Vietnamese.`,
    });

    res.json({ answer: response.text || "No response generated." });
  } catch (err: any) {
    handleApiError(res, err, "Failed to answer question.");
  }
});

// Audio file/blob transcription endpoint using Gemini Multimodal Audio
app.post("/api/transcribe-audio", async (req, res) => {
  try {
    const { audioBase64, mimeType = "audio/webm", targetLanguage = "en" } = req.body;

    if (!audioBase64) {
      return res.status(400).json({ error: "Audio data is required." });
    }

    const ai = getAiClient();

    const langInstruction = targetLanguage === "vi" 
      ? "Transcribe the spoken audio stream accurately into Vietnamese text. If English is spoken, transcribe it in English."
      : "Transcribe the spoken audio stream accurately into English text.";

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: [
        {
          inlineData: {
            mimeType: mimeType.split(";")[0], // Clean mimeType e.g. audio/webm
            data: audioBase64,
          },
        },
        {
          text: `${langInstruction} CRITICAL RULE: If the audio contains only silence, static, noise, or no recognizable human speech, respond with NOTHING (an empty text string). Do NOT hallucinate numbers, zeroes ("zero zero zero"), or repetitive filler words. Output ONLY the clean transcribed words if actual human speech is present.`,
        },
      ],
    });

    let rawTranscript = response.text ? response.text.trim() : "";
    
    // Filter out silence noise hallucinations like "zero zero zero" or repetitive "0"
    if (/^(zero|\s|0|\.|thank you|subtitles|amara\.org)+$/i.test(rawTranscript)) {
      rawTranscript = "";
    }

    res.json({ transcript: rawTranscript });
  } catch (err: any) {
    handleApiError(res, err, "Failed to transcribe audio.");
  }
});

async function startServer() {
  // Mount Vite dev server in non-production, static files in production
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server listening on http://0.0.0.0:${PORT}`);
  });
}

startServer();
