import { GoogleGenAI, Type } from "@google/genai";
import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "30mb" }));

// Helper to initialize server-side Gemini client securely
function getAiClient() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY environment variable is not defined.");
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
}

// Health check endpoint
app.get("/api/health", (_req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

// Test local Ollama / LM Studio endpoint reachability
app.post("/api/test-local-model", async (req, res) => {
  const { ollamaUrl = "http://localhost:11434", ollamaModel = "llama3.2" } = req.body;
  try {
    const cleanUrl = ollamaUrl.replace(/\/+$/, "");
    const testRes = await fetch(`${cleanUrl}/api/tags`, { method: "GET" });
    if (testRes.ok) {
      const data: any = await testRes.json();
      const models = data.models ? data.models.map((m: any) => m.name) : [];
      return res.json({
        status: "ok",
        message: `Kết nối thành công đến Local Ollama tại ${cleanUrl}!`,
        availableModels: models,
      });
    }
    return res.status(400).json({
      error: `Không thể kết nối đến Ollama tại ${cleanUrl}. Vui lòng mở Ollama và chạy: 'ollama run ${ollamaModel}'`,
    });
  } catch (err: any) {
    return res.status(500).json({
      error: `Chưa kết nối được Local LLM (${ollamaUrl}): ${err.message || 'Connection refused'}. Mẹo: Hãy dùng chế độ 'Local Fast (Chạy Offline SIÊU NHANH)' để dùng không cần tải server!`,
    });
  }
});

// Analyze session transcript endpoint
app.post("/api/analyze-session", async (req, res) => {
  try {
    const {
      transcript,
      durationSeconds = 0,
      topicHint = "",
      engineType = "gemini",
      ollamaUrl = "http://localhost:11434",
      ollamaModel = "llama3.2",
    } = req.body;

    if (!transcript || typeof transcript !== "string" || transcript.trim().length === 0) {
      return res.status(400).json({ error: "Transcript text is required for analysis." });
    }

    // Check if user requested Local Ollama server
    if (engineType === "local-ollama") {
      try {
        const cleanUrl = ollamaUrl.replace(/\/+$/, "");
        const ollamaPrompt = `You are a helpful AI note assistant. Analyze this transcript:
"${transcript}"

Return ONLY a valid JSON object with keys:
"title" (string, max 8 words),
"summary" (string, 2-4 sentences),
"keyTopics" (array of objects with "topic" string and "details" string array),
"actionItems" (array of strings),
"keyTakeaways" (array of strings),
"sentiment" (string, 1-3 words tone).`;

        const ollamaRes = await fetch(`${cleanUrl}/api/generate`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            model: ollamaModel,
            prompt: ollamaPrompt,
            stream: false,
            format: "json",
          }),
        });

        if (ollamaRes.ok) {
          const ollamaData: any = await ollamaRes.json();
          if (ollamaData.response) {
            const parsed = JSON.parse(ollamaData.response);
            return res.json({
              title: parsed.title || "Local Note Summary",
              summary: parsed.summary || "Summary generated by local model.",
              keyTopics: parsed.keyTopics || [{ topic: "Main Discussion", details: [transcript.slice(0, 100)] }],
              actionItems: parsed.actionItems || ["Review meeting notes"],
              keyTakeaways: parsed.keyTakeaways || ["Key takeaways extracted locally"],
              sentiment: parsed.sentiment || "Local Model Analysis",
              wordCount: transcript.split(/\s+/).length,
            });
          }
        }
      } catch (ollamaErr: any) {
        console.warn("Ollama local connection failed, falling back to local fast engine:", ollamaErr);
      }
    }

    const ai = getAiClient();

    const prompt = `You are an expert AI Assistant specialized in analyzing spoken meeting, lecture, podcast, and browser audio transcripts recorded in English.
Analyze the following transcript and generate comprehensive, highly structured notes, action items, summary, and insights.

${topicHint ? `User context/topic hint: ${topicHint}` : ""}
${durationSeconds ? `Audio duration: ${Math.round(durationSeconds)} seconds` : ""}

Transcript:
"""
${transcript}
"""

Return the output as a clean, structured JSON object with the following schema:
- title: A short, professional, descriptive title for this session (max 8 words).
- summary: A clear 2-4 sentence executive summary of what was discussed or presented.
- keyTopics: An array of objects, each containing:
  - topic: The name of the main subject/topic discussed.
  - details: An array of 2-4 specific bullet points detailing key facts, discussions, or code/tools mentioned under this topic.
- actionItems: An array of clear, actionable tasks or next steps implied or explicitly stated in the transcript. If none were mentioned, generate logical follow-up recommendations based on the content.
- keyTakeaways: An array of 3-5 core takeaways or memorable highlights from the session.
- sentiment: A 1-3 word classification of the session tone (e.g., "Professional & Analytical", "Casual Strategy Sync", "Technical Tutorial", "Brainstorming").
- wordCount: Total word count of the transcript.
`;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            title: { type: Type.STRING },
            summary: { type: Type.STRING },
            keyTopics: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  topic: { type: Type.STRING },
                  details: {
                    type: Type.ARRAY,
                    items: { type: Type.STRING },
                  },
                },
                required: ["topic", "details"],
              },
            },
            actionItems: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
            },
            keyTakeaways: {
              type: Type.ARRAY,
              items: { type: Type.STRING },
            },
            sentiment: { type: Type.STRING },
            wordCount: { type: Type.INTEGER },
          },
          required: ["title", "summary", "keyTopics", "actionItems", "keyTakeaways", "sentiment"],
        },
      },
    });

    const responseText = response.text;
    if (!responseText) {
      throw new Error("Empty response returned from Gemini API.");
    }

    const analysis = JSON.parse(responseText);
    res.json(analysis);
  } catch (err: any) {
    handleApiError(res, err, "Failed to analyze audio session");
  }
});

function handleApiError(res: express.Response, err: any, defaultMsg: string) {
  console.error("Gemini API Error:", err);
  const errMsg = err?.message || String(err);
  if (errMsg.includes("429") || errMsg.includes("RESOURCE_EXHAUSTED") || errMsg.includes("Quota exceeded")) {
    return res.status(429).json({
      error: "⚠️ Đã vượt quá hạn ngạch API Gemini miễn phí (20 request/ngày). Hãy chờ vài phút rồi bấm Phân tích AI lại! Lưu ý: Đoạn thu âm Web Speech API của bạn vẫn được lưu 100%."
    });
  }
  return res.status(500).json({ error: errMsg || defaultMsg });
}

// Q&A / Ask questions about session transcript endpoint
app.post("/api/ask-session", async (req, res) => {
  try {
    const {
      transcript,
      question,
      engineType = "gemini",
      ollamaUrl = "http://localhost:11434",
      ollamaModel = "llama3.2",
    } = req.body;

    if (!transcript || !question) {
      return res.status(400).json({ error: "Both transcript and question are required." });
    }

    if (engineType === "local-ollama") {
      try {
        const cleanUrl = ollamaUrl.replace(/\/+$/, "");
        const ollamaRes = await fetch(`${cleanUrl}/api/generate`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            model: ollamaModel,
            prompt: `Transcript context:\n"""\n${transcript}\n"""\n\nQuestion: "${question}"\n\nAnswer concisely based on the transcript context above:`,
            stream: false,
          }),
        });

        if (ollamaRes.ok) {
          const ollamaData: any = await ollamaRes.json();
          if (ollamaData.response) {
            return res.json({ answer: `💻 [Local Model (${ollamaModel})]: ${ollamaData.response}` });
          }
        }
      } catch (ollamaErr: any) {
        console.warn("Ollama ask-session failed, falling back to Gemini/Local Fast:", ollamaErr);
      }
    }

    const ai = getAiClient();

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: `You are an intelligent AI note assistant answering questions based strictly on a recorded English audio transcript.

Transcript context:
"""
${transcript}
"""

User Question: "${question}"

Provide a direct, helpful, and concise answer based on the transcript above. If the information isn't mentioned in the transcript, state so politely and provide your best relevant knowledge while clarifying it wasn't explicitly discussed in the recording. You may answer in English or Vietnamese if the question is in Vietnamese.`,
    });

    res.json({ answer: response.text || "No response generated." });
  } catch (err: any) {
    handleApiError(res, err, "Failed to answer question.");
  }
});

// Audio file/blob transcription endpoint using Gemini Multimodal Audio
app.post("/api/transcribe-audio", async (req, res) => {
  try {
    const { audioBase64, mimeType = "audio/webm", targetLanguage = "en" } = req.body;

    if (!audioBase64) {
      return res.status(400).json({ error: "Audio data is required." });
    }

    const ai = getAiClient();

    const langInstruction = targetLanguage === "vi" 
      ? "Transcribe the spoken audio stream accurately into Vietnamese text. If English is spoken, transcribe it in English."
      : "Transcribe the spoken audio stream accurately into English text.";

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: [
        {
          inlineData: {
            mimeType: mimeType.split(";")[0], // Clean mimeType e.g. audio/webm
            data: audioBase64,
          },
        },
        {
          text: `${langInstruction} CRITICAL RULE: If the audio contains only silence, static, noise, or no recognizable human speech, respond with NOTHING (an empty text string). Do NOT hallucinate numbers, zeroes ("zero zero zero"), or repetitive filler words. Output ONLY the clean transcribed words if actual human speech is present.`,
        },
      ],
    });

    let rawTranscript = response.text ? response.text.trim() : "";
    
    // Filter out silence noise hallucinations like "zero zero zero" or repetitive "0"
    if (/^(zero|\s|0|\.|thank you|subtitles|amara\.org)+$/i.test(rawTranscript)) {
      rawTranscript = "";
    }

    res.json({ transcript: rawTranscript });
  } catch (err: any) {
    handleApiError(res, err, "Failed to transcribe audio.");
  }
});

async function startServer() {
  // Mount Vite dev server in non-production, static files in production
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (_req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server listening on http://0.0.0.0:${PORT}`);
  });
}

startServer();
