import React, { useState } from 'react';
import { SessionAnalysis, ChatMessage } from '../types';
import { Sparkles, FileText, CheckSquare, Lightbulb, MessageSquare, Download, Send, RefreshCw, Copy, Check, Bookmark, Cpu, Zap, Terminal } from 'lucide-react';
import { LocalEngineConfig, generateLocalFastAnswer } from '../utils/localModelEngine';

interface AINotesPanelProps {
  analysis: SessionAnalysis | null;
  isAnalyzing: boolean;
  transcriptText: string;
  onReAnalyze?: () => void;
  engineConfig?: LocalEngineConfig;
}

export const AINotesPanel: React.FC<AINotesPanelProps> = ({
  analysis,
  isAnalyzing,
  transcriptText,
  onReAnalyze,
  engineConfig = { engineType: 'gemini', ollamaUrl: 'http://localhost:11434', ollamaModel: 'llama3.2' },
}) => {
  const [activeTab, setActiveTab] = useState<'summary' | 'topics' | 'actions' | 'ask' | 'export'>('summary');
  const [completedTasks, setCompletedTasks] = useState<Record<number, boolean>>({});
  
  // Ask AI Q&A Chat State
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [questionInput, setQuestionInput] = useState('');
  const [isAsking, setIsAsking] = useState(false);
  const [copiedNote, setCopiedNote] = useState(false);

  const toggleTask = (index: number) => {
    setCompletedTasks((prev) => ({ ...prev, [index]: !prev[index] }));
  };

  // Handle Q&A asking Gemini or Local AI about transcript
  const handleAskQuestion = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!questionInput.trim() || !transcriptText || isAsking) return;

    const userMsg: ChatMessage = {
      id: `user-${Date.now()}`,
      sender: 'user',
      text: questionInput.trim(),
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages((prev) => [...prev, userMsg]);
    setQuestionInput('');
    setIsAsking(true);

    try {
      if (engineConfig.engineType === 'local-fast') {
        // Fast local offline Q&A (0ms latency, 100% private)
        const fastAnswer = generateLocalFastAnswer(transcriptText, userMsg.text);
        const aiMsg: ChatMessage = {
          id: `ai-${Date.now()}`,
          sender: 'ai',
          text: fastAnswer,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        };
        setMessages((prev) => [...prev, aiMsg]);
      } else {
        const response = await fetch('/api/ask-session', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            transcript: transcriptText,
            question: userMsg.text,
            engineType: engineConfig.engineType,
            ollamaUrl: engineConfig.ollamaUrl,
            ollamaModel: engineConfig.ollamaModel,
          }),
        });

        const data = await response.json();
        if (!response.ok) {
          throw new Error(data.error || 'Failed to get answer');
        }

        const aiMsg: ChatMessage = {
          id: `ai-${Date.now()}`,
          sender: 'ai',
          text: data.answer,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        };

        setMessages((prev) => [...prev, aiMsg]);
      }
    } catch (err: any) {
      const errorMsg: ChatMessage = {
        id: `err-${Date.now()}`,
        sender: 'ai',
        text: `Error: ${err.message || 'Could not answer question.'}`,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      };
      setMessages((prev) => [...prev, errorMsg]);
    } finally {
      setIsAsking(false);
    }
  };

  // Format full Markdown for export
  const generateMarkdownExport = (): string => {
    if (!analysis) return '';

    let md = `# ${analysis.title}\n\n`;
    md += `**Tone/Sentiment:** ${analysis.sentiment}\n\n`;
    md += `## 📝 Executive Summary\n${analysis.summary}\n\n`;

    md += `## 🎯 Key Action Items\n`;
    analysis.actionItems.forEach((item, i) => {
      md += `- [ ] ${item}\n`;
    });
    md += `\n`;

    md += `## 📚 Topics & Key Points\n`;
    analysis.keyTopics.forEach((topic) => {
      md += `### ${topic.topic}\n`;
      topic.details.forEach((d) => {
        md += `- ${d}\n`;
      });
      md += `\n`;
    });

    md += `## 💡 Core Takeaways\n`;
    analysis.keyTakeaways.forEach((t) => {
      md += `- ${t}\n`;
    });
    md += `\n`;

    md += `---\n*Generated by StreamNote AI via Gemini 3.6 Flash*\n`;

    return md;
  };

  const handleDownloadFile = (content: string, filename: string, mime: string) => {
    const blob = new Blob([content], { type: mime });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleCopyNotes = () => {
    const md = generateMarkdownExport();
    navigator.clipboard.writeText(md);
    setCopiedNote(true);
    setTimeout(() => setCopiedNote(false), 2000);
  };

  // Loading state
  if (isAnalyzing) {
    return (
      <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-8 flex flex-col items-center justify-center text-center space-y-4 h-[480px]">
        <div className="w-16 h-16 rounded-2xl bg-purple-50 dark:bg-purple-950/60 text-purple-600 dark:text-purple-400 flex items-center justify-center animate-bounce shadow-lg shadow-purple-500/10">
          <Sparkles className="w-8 h-8 animate-spin text-purple-500" />
        </div>
        <div>
          <h3 className="text-base font-bold text-slate-900 dark:text-white">
            Gemini AI is Analyzing Session...
          </h3>
          <p className="text-xs text-slate-500 dark:text-slate-400 max-w-sm mt-1">
            Extracting executive summary, topic outlines, action items, and key takeaways from English speech stream.
          </p>
        </div>
        <div className="w-48 h-2 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
          <div className="h-full bg-gradient-to-r from-purple-500 to-indigo-500 animate-pulse w-3/4 rounded-full" />
        </div>
      </div>
    );
  }

  // Empty state when session not analyzed yet
  if (!analysis) {
    return (
      <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 p-8 flex flex-col items-center justify-center text-center h-[480px]">
        <div className="w-14 h-14 rounded-2xl bg-indigo-50 dark:bg-indigo-950/50 text-indigo-500 flex items-center justify-center mb-4">
          <FileText className="w-7 h-7" />
        </div>
        <h3 className="text-sm font-bold text-slate-900 dark:text-white">
          AI Automated Notes Pending
        </h3>
        <p className="text-xs text-slate-500 dark:text-slate-400 max-w-xs mt-1 mb-4">
          Click <span className="font-semibold text-red-600 dark:text-red-400">END</span> on an active audio stream or load a demo session to automatically generate AI notes & analysis.
        </p>
        {onReAnalyze && transcriptText.length > 0 && (
          <button
            type="button"
            onClick={onReAnalyze}
            className="px-4 py-2 rounded-xl bg-purple-600 hover:bg-purple-700 text-white text-xs font-semibold flex items-center gap-2 shadow-sm transition-colors"
          >
            <Sparkles className="w-3.5 h-3.5" />
            <span>Generate AI Notes Now</span>
          </button>
        )}
      </div>
    );
  }

  return (
    <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col h-[480px] overflow-hidden">
      {/* Header bar */}
      <div className="p-4 border-b border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/50 flex flex-wrap items-center justify-between gap-3">
        <div>
          <div className="flex items-center gap-2">
            <span className="p-1.5 rounded-md bg-purple-100 dark:bg-purple-950/80 text-purple-600 dark:text-purple-300">
              <Sparkles className="w-4 h-4" />
            </span>
            <h3 className="font-bold text-slate-900 dark:text-white text-sm line-clamp-1">
              {analysis.title}
            </h3>
          </div>
          <div className="flex items-center gap-2 mt-1">
            <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-purple-50 dark:bg-purple-950/60 text-purple-700 dark:text-purple-300 border border-purple-200 dark:border-purple-800">
              {analysis.sentiment}
            </span>
            <span className="text-xs text-slate-500">
              {analysis.actionItems.length} action items &bull; {analysis.keyTopics.length} topics
            </span>
          </div>
        </div>

        {/* Tab Navigation Buttons */}
        <div className="flex items-center gap-1 bg-slate-100 dark:bg-slate-800 p-1 rounded-xl text-xs font-medium">
          <button
            id="tab-summary-btn"
            onClick={() => setActiveTab('summary')}
            className={`px-2.5 py-1 rounded-lg transition-all flex items-center gap-1 ${
              activeTab === 'summary'
                ? 'bg-white dark:bg-slate-700 text-slate-900 dark:text-white shadow-2xs font-semibold'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            <FileText className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Notes</span>
          </button>

          <button
            id="tab-topics-btn"
            onClick={() => setActiveTab('topics')}
            className={`px-2.5 py-1 rounded-lg transition-all flex items-center gap-1 ${
              activeTab === 'topics'
                ? 'bg-white dark:bg-slate-700 text-slate-900 dark:text-white shadow-2xs font-semibold'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            <Bookmark className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Topics</span>
          </button>

          <button
            id="tab-actions-btn"
            onClick={() => setActiveTab('actions')}
            className={`px-2.5 py-1 rounded-lg transition-all flex items-center gap-1 ${
              activeTab === 'actions'
                ? 'bg-white dark:bg-slate-700 text-slate-900 dark:text-white shadow-2xs font-semibold'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            <CheckSquare className="w-3.5 h-3.5 text-emerald-500" />
            <span className="hidden sm:inline">Tasks</span>
          </button>

          <button
            id="tab-ask-btn"
            onClick={() => setActiveTab('ask')}
            className={`px-2.5 py-1 rounded-lg transition-all flex items-center gap-1 ${
              activeTab === 'ask'
                ? 'bg-white dark:bg-slate-700 text-purple-600 dark:text-purple-300 shadow-2xs font-semibold'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            <MessageSquare className="w-3.5 h-3.5 text-purple-500" />
            <span className="hidden sm:inline">Ask AI</span>
          </button>

          <button
            id="tab-export-btn"
            onClick={() => setActiveTab('export')}
            className={`px-2.5 py-1 rounded-lg transition-all flex items-center gap-1 ${
              activeTab === 'export'
                ? 'bg-white dark:bg-slate-700 text-slate-900 dark:text-white shadow-2xs font-semibold'
                : 'text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white'
            }`}
          >
            <Download className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      {/* Content Body */}
      <div className="flex-1 p-5 overflow-y-auto">
        {/* TAB 1: EXECUTIVE SUMMARY & TAKEAWAYS */}
        {activeTab === 'summary' && (
          <div className="space-y-5 text-sm">
            {/* Summary Box */}
            <div className="p-4 rounded-xl bg-purple-50/60 dark:bg-purple-950/30 border border-purple-200/80 dark:border-purple-900/60 space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-purple-900 dark:text-purple-300 flex items-center gap-1.5">
                <FileText className="w-4 h-4 text-purple-600" /> Executive Summary
              </h4>
              <p className="text-slate-800 dark:text-slate-200 leading-relaxed text-sm">
                {analysis.summary}
              </p>
            </div>

            {/* Core Takeaways */}
            <div className="space-y-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 flex items-center gap-1.5">
                <Lightbulb className="w-4 h-4 text-amber-500" /> Core Session Highlights
              </h4>
              <div className="grid grid-cols-1 gap-2">
                {analysis.keyTakeaways.map((takeaway, idx) => (
                  <div
                    key={idx}
                    className="p-3 rounded-xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/60 dark:border-slate-800 flex items-start gap-2.5"
                  >
                    <span className="w-5 h-5 rounded-full bg-indigo-100 dark:bg-indigo-950 text-indigo-700 dark:text-indigo-300 text-xs font-bold flex items-center justify-center shrink-0 mt-0.5">
                      {idx + 1}
                    </span>
                    <p className="text-slate-700 dark:text-slate-300 text-xs leading-relaxed">
                      {takeaway}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}

        {/* TAB 2: TOPICS OUTLINE */}
        {activeTab === 'topics' && (
          <div className="space-y-4">
            <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Session Topic Breakdown
            </h4>
            <div className="space-y-3">
              {analysis.keyTopics.map((item, idx) => (
                <div
                  key={idx}
                  className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200 dark:border-slate-800 space-y-2"
                >
                  <h5 className="font-semibold text-slate-900 dark:text-white text-sm flex items-center gap-2">
                    <span className="w-2 h-2 rounded-full bg-indigo-500" />
                    {item.topic}
                  </h5>
                  <ul className="space-y-1.5 pl-4">
                    {item.details.map((detail, dIdx) => (
                      <li key={dIdx} className="text-xs text-slate-600 dark:text-slate-300 list-disc">
                        {detail}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* TAB 3: ACTION ITEMS */}
        {activeTab === 'actions' && (
          <div className="space-y-4">
            <div className="flex items-center justify-between">
              <h4 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                Action Items & Next Steps
              </h4>
              <span className="text-xs text-slate-500">
                {Object.values(completedTasks).filter(Boolean).length} of {analysis.actionItems.length} done
              </span>
            </div>

            <div className="space-y-2">
              {analysis.actionItems.map((action, idx) => {
                const isChecked = !!completedTasks[idx];
                return (
                  <div
                    key={idx}
                    onClick={() => toggleTask(idx)}
                    className={`p-3.5 rounded-xl border transition-all cursor-pointer flex items-start gap-3 ${
                      isChecked
                        ? 'bg-emerald-50/60 dark:bg-emerald-950/30 border-emerald-200 dark:border-emerald-900/60 text-slate-500 line-through'
                        : 'bg-slate-50 dark:bg-slate-800/60 border-slate-200 dark:border-slate-800 text-slate-800 dark:text-slate-200 hover:border-indigo-300'
                    }`}
                  >
                    <input
                      type="checkbox"
                      checked={isChecked}
                      onChange={() => toggleTask(idx)}
                      className="mt-0.5 rounded text-indigo-600 focus:ring-indigo-500 w-4 h-4"
                    />
                    <span className="text-xs font-medium leading-relaxed">{action}</span>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* TAB 4: ASK AI Q&A CHAT */}
        {activeTab === 'ask' && (
          <div className="flex flex-col h-full space-y-3">
            <div className="flex-1 overflow-y-auto space-y-3 p-1">
              {messages.length === 0 ? (
                <div className="text-center py-8 text-slate-400 space-y-2">
                  <MessageSquare className="w-8 h-8 text-purple-400 mx-auto" />
                  <p className="text-xs font-medium text-slate-700 dark:text-slate-300">
                    Ask Gemini anything about this session
                  </p>
                  <p className="text-[11px] text-slate-500 max-w-xs mx-auto">
                    Try asking: "What were the main decisions?", "Summarize the tech requirements", or "Did anyone mention deadlines?"
                  </p>
                </div>
              ) : (
                messages.map((msg) => (
                  <div
                    key={msg.id}
                    className={`flex flex-col ${
                      msg.sender === 'user' ? 'items-end' : 'items-start'
                    }`}
                  >
                    <div
                      className={`max-w-[85%] rounded-2xl p-3 text-xs leading-relaxed ${
                        msg.sender === 'user'
                          ? 'bg-indigo-600 text-white rounded-br-xs'
                          : 'bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-slate-200 rounded-bl-xs border border-slate-200 dark:border-slate-700'
                      }`}
                    >
                      {msg.text}
                    </div>
                    <span className="text-[10px] text-slate-400 mt-1 px-1">
                      {msg.timestamp}
                    </span>
                  </div>
                ))
              )}
              {isAsking && (
                <div className="flex items-center gap-2 text-xs text-purple-600 dark:text-purple-400">
                  <Sparkles className="w-3.5 h-3.5 animate-spin" />
                  <span>Gemini is generating response...</span>
                </div>
              )}
            </div>

            <form onSubmit={handleAskQuestion} className="flex gap-2 pt-2 border-t border-slate-100 dark:border-slate-800">
              <input
                type="text"
                value={questionInput}
                onChange={(e) => setQuestionInput(e.target.value)}
                placeholder="Ask AI about this session transcript..."
                className="flex-1 text-xs px-3.5 py-2 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 text-slate-900 dark:text-white focus:outline-hidden focus:ring-1 focus:ring-purple-500"
              />
              <button
                type="submit"
                disabled={!questionInput.trim() || isAsking}
                className="px-3.5 py-2 bg-purple-600 hover:bg-purple-700 text-white rounded-xl text-xs font-medium disabled:opacity-50 transition-colors flex items-center justify-center"
              >
                <Send className="w-4 h-4" />
              </button>
            </form>
          </div>
        )}

        {/* TAB 5: EXPORT MENU */}
        {activeTab === 'export' && (
          <div className="space-y-4 text-xs">
            <h4 className="font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Export AI Notes & Transcript
            </h4>
            
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              <button
                id="export-md-btn"
                type="button"
                onClick={() =>
                  handleDownloadFile(
                    generateMarkdownExport(),
                    `${analysis.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_notes.md`,
                    'text/markdown'
                  )
                }
                className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors text-left space-y-1"
              >
                <div className="font-semibold text-slate-900 dark:text-white flex items-center justify-between">
                  <span>Markdown File (.md)</span>
                  <Download className="w-4 h-4 text-indigo-500" />
                </div>
                <p className="text-slate-500 text-[11px]">Formatted structured notes for Notion, Obsidian, or GitHub.</p>
              </button>

              <button
                id="export-json-btn"
                type="button"
                onClick={() =>
                  handleDownloadFile(
                    JSON.stringify(analysis, null, 2),
                    `${analysis.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_analysis.json`,
                    'application/json'
                  )
                }
                className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/80 border border-slate-200 dark:border-slate-700 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors text-left space-y-1"
              >
                <div className="font-semibold text-slate-900 dark:text-white flex items-center justify-between">
                  <span>JSON Payload (.json)</span>
                  <Download className="w-4 h-4 text-emerald-500" />
                </div>
                <p className="text-slate-500 text-[11px]">Raw structured JSON format for developers and databases.</p>
              </button>
            </div>

            <div className="pt-2 flex justify-end">
              <button
                id="copy-all-md-btn"
                type="button"
                onClick={handleCopyNotes}
                className="px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white rounded-xl font-medium text-xs flex items-center gap-2 shadow-xs transition-colors"
              >
                {copiedNote ? <Check className="w-4 h-4 text-emerald-300" /> : <Copy className="w-4 h-4" />}
                <span>{copiedNote ? 'Copied Markdown' : 'Copy All Notes as Markdown'}</span>
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
